# AUTOGENERATED FILE; DO NOT MODIFY (use `build.py` instead)
CFLAGS+=-DPROJECT_VERSION=0.1.0 -D_POSIX_C_SOURCE=200809L -O2 -Wall -Werror -Wextra -Wno-error=deprecated-declarations -Wno-error=missing-field-initializers -Wno-error=pedantic -Wno-error=reorder -Wno-error=unused-parameter -falign-functions=32 -march=native -mtune=native -pedantic -std=c99
LDFLAGS+=-static -static-libgcc
INCLUDES+=-Isrc/

.PHONY: default all test
default: test
	./build/test

all: seadragon test

HEADERS=src/ast.h src/lexer.h src/list.h src/parser.h src/sema.h src/token.h test/test.h
build/obj/%.o: %.c $(HEADERS)
	$(CC) $< $(CFLAGS) $(EXTRA_CFLAGS) $(INCLUDES) -c -o $@

### TARGET: seadragon

seadragon_OBJECTS = build/obj/src/lexer.o build/obj/src/list.o build/obj/src/parser.o build/obj/src/sema.o build/obj/src/token.o
$(seadragon_OBJECTS): EXTRA_CFLAGS := 

seadragon_HEADERS = src/ast.h src/lexer.h src/list.h src/parser.h src/sema.h src/token.h


### TARGET: test

test: build/test

test_OBJECTS = build/obj/test/main.o
$(test_OBJECTS): EXTRA_CFLAGS := 

test_HEADERS = test/test.h

build/test: $(test_OBJECTS)  $(seadragon_OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
