# AUTOGENERATED FILE; DO NOT MODIFY (use `build.py` instead)
CFLAGS+=-DPROJECT_VERSION=0.1.0-54 -D_DEBUG -D_POSIX_C_SOURCE=200809L -Og -Wall -g -pedantic -std=c99
LDFLAGS+=
INCLUDES+=-Isrc/

.PHONY: default all test
default: test
	./build/test

all: seadragon test

HEADERS=src/lexer.h src/token.h test/test.h
build/obj/%.o: %.c $(HEADERS)
	$(CC) $< $(CFLAGS) $(EXTRA_CFLAGS) $(INCLUDES) -c -o $@

### TARGET: seadragon

seadragon_OBJECTS = build/obj/src/lexer.o build/obj/src/token.o
$(seadragon_OBJECTS): EXTRA_CFLAGS := 

seadragon_HEADERS = src/lexer.h src/token.h


### TARGET: test

test: build/test

test_OBJECTS = build/obj/test/main.o
$(test_OBJECTS): EXTRA_CFLAGS := 

test_HEADERS = test/test.h

build/test: $(test_OBJECTS)  $(seadragon_OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
